### ISSUE TITLE
Allow auto-toggling the Twitch extension when switching games

### ISSUE THREAD

**Issue by francislavoie** [MaT1g3R/slay-the-relics#17]
According to https://help.twitch.tv/s/article/extensions-switch-with-your-game-selection, Twitch extensions are able to toggle themselves on automatically when a streamer switches games.

For example, under `My Extensions -> Permissions` on the Twitch dashboard, you can see this for extensions that have this feature:

![image](https://github.com/MaT1g3R/slay-the-relics/assets/2111701/0819efea-62b5-4306-a366-f228886e09db)

It also has a similar mention under "My Extensions", the PoE one mentions it'll automatically toggle itself on but Slay the Relics doesn't :disappointed: 

![image](https://github.com/MaT1g3R/slay-the-relics/assets/2111701/804d24c5-262f-49f8-8b53-04bea9dcc6ef)

My hunch is that it might be dependent on the "Game Category" set for the extension. Was it set to have "Slay the Spire"? (I tried creating a dummy extension real quick to see how configuration for it works)

I couldn't find any other documentation about how this functionality works, all of Twitch's developer docs doesn't mention anything about this as far as I could tell.

I also found this old article https://medium.com/@owlsquid/dynamic-managment-for-extensions-a3b845a1c2f4 from 2019 which looks very similar to the help doc above :point_up: which mentions a beta list of extensions that support that feature. Maybe it has to be toggled on by a Twitch employee?? :grimacing: I hope that's not the case, that would be annoying.

For context: I moderate for a medium-sized streamer, he streams multiple different games per stream (~3 different games, ~2 hours each) and if he happens to stream 2 games which have extensions in a row (where one is StS), it's annoying to have to go in the Twitch dashboard to switch extensions manually. In theory it should _just work_ but since StR doesn't support it, it adds friction. Often we forget until someone in chat asks "hey the overlay isn't working" etc. So it would be awesome if it worked!

**Comment by MaT1g3R** [comment]
I've already set the game category to StS, so I don't think that's it. I don't see any other configuration that allows me to do this, and if that configuration existed I wouldn't be able to change it right now since Twitch paused reviewing extensions. I check a few other overlay extensions and most of them don't seem to have this feature. It looks like it could be a beta feature that never got completed.

**Comment by francislavoie** [comment]
https://dev.twitch.tv/docs/extensions/

> Reviews for Extensions have resumed in May 2024 and the backlog will be completed in the coming weeks. Reviews for organizations, games, and chatbot verification continue to be temporarily paused while we revise our processes. Thank you for your patience and understanding.

I actually see it on most of the overlays I've tried. Hearthstone deck tracker, PoE, Baldur's gate 3, etc. StR is the one I don't see it on.

**Comment by MaT1g3R** [comment]
There is essentially nothing I can do to enable this. I can't find any info on how this feature works.

**Comment by MaT1g3R** [comment]
https://discuss.dev.twitch.com/t/switching-extensions/34803/2

This is their response in 2021 suggesting it's an internal allow list

**Comment by francislavoie** [comment]
Considering a lot of extensions for games newer than 2021 have it (e.g. baldur's gate 3) there must be a way to ask them to add it :man_shrugging: Maybe we need to ask on that forum.

**Comment by francislavoie** [comment]
https://discuss.dev.twitch.com/t/enable-auto-switching-for-an-extension/59643

**Comment by francislavoie** [comment]
:roll_eyes: apparently they only enable that for official game extensions. Very annoying.

**Comment by MaT1g3R** [comment]
That is disappointing to read, thank you for checking with Twitch

**Comment by BarryCarlyon** [comment]
It's also basically a "dead" feature I don't think anything has been set to use this feature of late anyway
